### ISSUE TITLE
Can not open Hysitron example file?

### ISSUE THREAD

**Issue by MGRashed** [DavidMercier/TriDiMap#24]
Error occurs when trying to open Hysitron example file, can this be fixed?

Error message:

_User selected: C:\TriDiMap-master\data_indentation\Hysitron_example_10x10.xlsx_
_No Excel sheet named:Hysitron_example_10x10found in the Excel file !_
_No elastic modulus values found !_
_No hardness values found !_
_Reference to non-existent field 'expValues_mat'._

_Error in TriDiMap_loadingMeanData (line 352)
    minVal =
    round(100*(nanmin(nanmin(data.expValues_mat.H))))/100;_
 
_Error while evaluating UIControl Callback._

**Comment by DavidMercier** [comment]
Hi,

For me no bug. Have you set Hysitron and 10x10 in the settings (top left corner of the GUI). See attached screenshot of the result when you load the Hysitron example file.
Is it the one given in the TriDiMap repository or another one from you ?
Thanks for your feedback.
![capture](https://user-images.githubusercontent.com/8429951/52518321-3bdbb500-2c49-11e9-8f1d-871741eb2df7.PNG)

**Comment by DavidMercier** [comment]
In any case, download the last version of TriDiMap...It might happen if you have an old version.

**Comment by MGRashed** [comment]
My apologies, you are quite right. It's working now.
