### ISSUE TITLE
Average hardness value is being overestimated

### ISSUE THREAD

**Issue by MGRashed** [DavidMercier/TriDiMap#25]
Average hardness value is being overestimated, also requesting to add standard deviation value.

**Comment by DavidMercier** [comment]
Can you describe a bit more this request/issue ?
There is onto the GUI, mean mechanical properties values displayed with STD. On the map, it is not average values, but values of mechanical properties at a given X-Y position and a given depth (usually maximum of indentation test).

**Comment by MGRashed** [comment]
Mean property value is showing a higher value than the average. What I meant by showing STD as well, is to have another box beside Mean property value (e.g. Average ± STD or, 2.71 ± 0.33 GPa)

**Comment by DavidMercier** [comment]
I get it. The arithmetic mean value is obtained using this Matlab function:
https://www.mathworks.com/help/matlab/ref/mean.html
I think your average value is calculated using median function:
https://www.mathworks.com/help/matlab/ref/median.html
I prefer by default to give the mean, but in case it is easy to change in the code for you...
By the way, I add the std calculation, which is useful.

**Comment by MGRashed** [comment]
If I open a nano indentation excel file and do a average of hardness in excel, then it comes out to be smaller than what TriDiMap is reporting. My data is from Hysitron (3 by 4 grid), though the example Hysitron (10 by 10 grid) is giving correct mean. Is there any problem happening when the grid is not square?

**Comment by DavidMercier** [comment]
Done
